### ISSUE TITLE
Clearer install instructions

### ISSUE THREAD

**Issue by Harry-Harrison** [Secretmapper/combustion#11] opened 2017-04-12 08:55 UTC
I'm trying to set Combustion up on my Raspberry Pi 3 box, but I'm getting no-where. If someone can walk me through the steps I'd be happy to test and write out some friendly instructions 👍 

Sorry to sound like such a dweeb!

**Comment by andyts93** [comment] 2017-04-13 09:31
I was not able to install it setting TRANSMISSION_WEB_HOME variable so here's my step to test this web ui

```
# go to transmission web interface folder
cd /usr/share/transmission

# rename the web folder so you have a backup
mv web web-default

# download combustion release and extract it
wget https://github.com/Secretmapper/combustion/archive/release.zip && unzip release.zip

# rename release to web folder
mv release web
```

**Comment by Harry-Harrison** [comment] 2017-04-13 09:31
@andyts93 That's exactly what I was going to try later on tonight :)

**Comment by Secretmapper** [comment] 2017-04-13 09:47
Sorry, been quite busy lately!

Yup indeed replacing the default web theme from the folder itself is a lot easier. I'll add that to the README, thanks  @andyts93 and @Harry-Harrison !

Closing this as the issue is resolved. Let me know if you still have any questions/suggestions

**Closed by Secretmapper** 2017-04-13 09:47 UTC
